# pylint: skip-file
# Generated by Django 3.2.4 on 2021-07-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine_builder', '0002_alter_interactioncard_id'),
        ('django_dialog_engine_builder', '0002_auto_20210624_1938'),
    ]

    operations = [
    ]
