# pylint: skip-file
# Generated by Django 3.2.7 on 2021-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_dialog_engine_builder', '0004_auto_20210922_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactioncard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
